import { z } from 'zod';
export declare const GeneroEnum: z.ZodEnum<["M", "F"]>;
export declare const PapelEnum: z.ZodEnum<["encontrista", "servo"]>;
export declare const StatusPagamentoEnum: z.ZodEnum<["pendente", "pago_parcial", "pago_total"]>;
export declare const StatusEventoEnum: z.ZodEnum<["rascunho", "aberto", "encerrado", "realizado"]>;
export declare const FormaPagamentoEnum: z.ZodEnum<["pix", "dinheiro", "cartao", "outro"]>;
export declare const CategoriaDespesaEnum: z.ZodEnum<["alimentacao", "transporte", "material", "hospedagem", "outro"]>;
export declare const GeneroQuartoEnum: z.ZodEnum<["M", "F", "MISTO"]>;
export declare const TipoCamaEnum: z.ZodEnum<["solteiro", "beliche_superior", "beliche_inferior", "casal"]>;
export declare const UserRoleEnum: z.ZodEnum<["admin", "lider", "servo"]>;
export declare const PessoaSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    nome: z.ZodString;
    genero: z.ZodEnum<["M", "F"]>;
    data_nascimento: z.ZodOptional<z.ZodString>;
    telefone: z.ZodOptional<z.ZodString>;
    email: z.ZodOptional<z.ZodString>;
    padrinho_id: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    alergias: z.ZodOptional<z.ZodString>;
    restricoes_alimentares: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    medicamentos: z.ZodOptional<z.ZodString>;
    condicoes_medicas: z.ZodOptional<z.ZodString>;
    contato_emergencia_nome: z.ZodOptional<z.ZodString>;
    contato_emergencia_tel: z.ZodOptional<z.ZodString>;
    created_at: z.ZodOptional<z.ZodString>;
    updated_at: z.ZodOptional<z.ZodString>;
    deleted_at: z.ZodOptional<z.ZodNullable<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    nome: string;
    genero: "M" | "F";
    id?: string | undefined;
    data_nascimento?: string | undefined;
    telefone?: string | undefined;
    email?: string | undefined;
    padrinho_id?: string | null | undefined;
    alergias?: string | undefined;
    restricoes_alimentares?: string[] | undefined;
    medicamentos?: string | undefined;
    condicoes_medicas?: string | undefined;
    contato_emergencia_nome?: string | undefined;
    contato_emergencia_tel?: string | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
    deleted_at?: string | null | undefined;
}, {
    nome: string;
    genero: "M" | "F";
    id?: string | undefined;
    data_nascimento?: string | undefined;
    telefone?: string | undefined;
    email?: string | undefined;
    padrinho_id?: string | null | undefined;
    alergias?: string | undefined;
    restricoes_alimentares?: string[] | undefined;
    medicamentos?: string | undefined;
    condicoes_medicas?: string | undefined;
    contato_emergencia_nome?: string | undefined;
    contato_emergencia_tel?: string | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
    deleted_at?: string | null | undefined;
}>;
export declare const LocalSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    nome: z.ZodString;
    endereco: z.ZodOptional<z.ZodString>;
    capacidade_total: z.ZodOptional<z.ZodNumber>;
    created_at: z.ZodOptional<z.ZodString>;
    updated_at: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    nome: string;
    id?: string | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
    endereco?: string | undefined;
    capacidade_total?: number | undefined;
}, {
    nome: string;
    id?: string | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
    endereco?: string | undefined;
    capacidade_total?: number | undefined;
}>;
export declare const QuartoSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    local_id: z.ZodString;
    nome: z.ZodString;
    genero_permitido: z.ZodEnum<["M", "F", "MISTO"]>;
    capacidade: z.ZodNumber;
    created_at: z.ZodOptional<z.ZodString>;
    updated_at: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    nome: string;
    local_id: string;
    genero_permitido: "M" | "F" | "MISTO";
    capacidade: number;
    id?: string | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
}, {
    nome: string;
    local_id: string;
    genero_permitido: "M" | "F" | "MISTO";
    capacidade: number;
    id?: string | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
}>;
export declare const CamaSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    quarto_id: z.ZodString;
    identificacao: z.ZodString;
    tipo: z.ZodEnum<["solteiro", "beliche_superior", "beliche_inferior", "casal"]>;
    created_at: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    quarto_id: string;
    identificacao: string;
    tipo: "solteiro" | "beliche_superior" | "beliche_inferior" | "casal";
    id?: string | undefined;
    created_at?: string | undefined;
}, {
    quarto_id: string;
    identificacao: string;
    tipo: "solteiro" | "beliche_superior" | "beliche_inferior" | "casal";
    id?: string | undefined;
    created_at?: string | undefined;
}>;
export declare const EventoSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    nome: z.ZodString;
    descricao: z.ZodOptional<z.ZodString>;
    data_inicio: z.ZodString;
    data_fim: z.ZodString;
    local_id: z.ZodString;
    valor_inscricao_encontrista: z.ZodNumber;
    valor_inscricao_servo: z.ZodNumber;
    capacidade_maxima: z.ZodNumber;
    status: z.ZodEnum<["rascunho", "aberto", "encerrado", "realizado"]>;
    created_at: z.ZodOptional<z.ZodString>;
    updated_at: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    status: "rascunho" | "aberto" | "encerrado" | "realizado";
    nome: string;
    local_id: string;
    data_inicio: string;
    data_fim: string;
    valor_inscricao_encontrista: number;
    valor_inscricao_servo: number;
    capacidade_maxima: number;
    id?: string | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
    descricao?: string | undefined;
}, {
    status: "rascunho" | "aberto" | "encerrado" | "realizado";
    nome: string;
    local_id: string;
    data_inicio: string;
    data_fim: string;
    valor_inscricao_encontrista: number;
    valor_inscricao_servo: number;
    capacidade_maxima: number;
    id?: string | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
    descricao?: string | undefined;
}>;
export declare const InscricaoSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    evento_id: z.ZodString;
    pessoa_id: z.ZodString;
    papel: z.ZodEnum<["encontrista", "servo"]>;
    valor_total: z.ZodNumber;
    valor_pago: z.ZodNumber;
    cama_id: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    observacoes: z.ZodOptional<z.ZodString>;
    created_at: z.ZodOptional<z.ZodString>;
    updated_at: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    evento_id: string;
    pessoa_id: string;
    papel: "encontrista" | "servo";
    valor_total: number;
    valor_pago: number;
    id?: string | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
    cama_id?: string | null | undefined;
    observacoes?: string | undefined;
}, {
    evento_id: string;
    pessoa_id: string;
    papel: "encontrista" | "servo";
    valor_total: number;
    valor_pago: number;
    id?: string | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
    cama_id?: string | null | undefined;
    observacoes?: string | undefined;
}>;
export declare const PagamentoSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    inscricao_id: z.ZodString;
    valor: z.ZodNumber;
    forma_pagamento: z.ZodEnum<["pix", "dinheiro", "cartao", "outro"]>;
    data_pagamento: z.ZodString;
    comprovante_url: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    registrado_por: z.ZodOptional<z.ZodString>;
    created_at: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    inscricao_id: string;
    valor: number;
    forma_pagamento: "pix" | "dinheiro" | "cartao" | "outro";
    data_pagamento: string;
    id?: string | undefined;
    created_at?: string | undefined;
    comprovante_url?: string | null | undefined;
    registrado_por?: string | undefined;
}, {
    inscricao_id: string;
    valor: number;
    forma_pagamento: "pix" | "dinheiro" | "cartao" | "outro";
    data_pagamento: string;
    id?: string | undefined;
    created_at?: string | undefined;
    comprovante_url?: string | null | undefined;
    registrado_por?: string | undefined;
}>;
export declare const DespesaSchema: z.ZodObject<{
    id: z.ZodOptional<z.ZodString>;
    evento_id: z.ZodString;
    descricao: z.ZodString;
    categoria: z.ZodEnum<["alimentacao", "transporte", "material", "hospedagem", "outro"]>;
    valor: z.ZodNumber;
    data_despesa: z.ZodString;
    comprovante_url: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    registrado_por: z.ZodOptional<z.ZodString>;
    created_at: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    descricao: string;
    evento_id: string;
    valor: number;
    categoria: "outro" | "alimentacao" | "transporte" | "material" | "hospedagem";
    data_despesa: string;
    id?: string | undefined;
    created_at?: string | undefined;
    comprovante_url?: string | null | undefined;
    registrado_por?: string | undefined;
}, {
    descricao: string;
    evento_id: string;
    valor: number;
    categoria: "outro" | "alimentacao" | "transporte" | "material" | "hospedagem";
    data_despesa: string;
    id?: string | undefined;
    created_at?: string | undefined;
    comprovante_url?: string | null | undefined;
    registrado_por?: string | undefined;
}>;
export declare const CreatePessoaDTO: z.ZodObject<Omit<{
    id: z.ZodOptional<z.ZodString>;
    nome: z.ZodString;
    genero: z.ZodEnum<["M", "F"]>;
    data_nascimento: z.ZodOptional<z.ZodString>;
    telefone: z.ZodOptional<z.ZodString>;
    email: z.ZodOptional<z.ZodString>;
    padrinho_id: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    alergias: z.ZodOptional<z.ZodString>;
    restricoes_alimentares: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    medicamentos: z.ZodOptional<z.ZodString>;
    condicoes_medicas: z.ZodOptional<z.ZodString>;
    contato_emergencia_nome: z.ZodOptional<z.ZodString>;
    contato_emergencia_tel: z.ZodOptional<z.ZodString>;
    created_at: z.ZodOptional<z.ZodString>;
    updated_at: z.ZodOptional<z.ZodString>;
    deleted_at: z.ZodOptional<z.ZodNullable<z.ZodString>>;
}, "id" | "created_at" | "updated_at" | "deleted_at">, "strip", z.ZodTypeAny, {
    nome: string;
    genero: "M" | "F";
    data_nascimento?: string | undefined;
    telefone?: string | undefined;
    email?: string | undefined;
    padrinho_id?: string | null | undefined;
    alergias?: string | undefined;
    restricoes_alimentares?: string[] | undefined;
    medicamentos?: string | undefined;
    condicoes_medicas?: string | undefined;
    contato_emergencia_nome?: string | undefined;
    contato_emergencia_tel?: string | undefined;
}, {
    nome: string;
    genero: "M" | "F";
    data_nascimento?: string | undefined;
    telefone?: string | undefined;
    email?: string | undefined;
    padrinho_id?: string | null | undefined;
    alergias?: string | undefined;
    restricoes_alimentares?: string[] | undefined;
    medicamentos?: string | undefined;
    condicoes_medicas?: string | undefined;
    contato_emergencia_nome?: string | undefined;
    contato_emergencia_tel?: string | undefined;
}>;
export declare const UpdatePessoaDTO: z.ZodObject<{
    nome: z.ZodOptional<z.ZodString>;
    genero: z.ZodOptional<z.ZodEnum<["M", "F"]>>;
    data_nascimento: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    telefone: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    email: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    padrinho_id: z.ZodOptional<z.ZodOptional<z.ZodNullable<z.ZodString>>>;
    alergias: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    restricoes_alimentares: z.ZodOptional<z.ZodOptional<z.ZodArray<z.ZodString, "many">>>;
    medicamentos: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    condicoes_medicas: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    contato_emergencia_nome: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    contato_emergencia_tel: z.ZodOptional<z.ZodOptional<z.ZodString>>;
}, "strip", z.ZodTypeAny, {
    nome?: string | undefined;
    genero?: "M" | "F" | undefined;
    data_nascimento?: string | undefined;
    telefone?: string | undefined;
    email?: string | undefined;
    padrinho_id?: string | null | undefined;
    alergias?: string | undefined;
    restricoes_alimentares?: string[] | undefined;
    medicamentos?: string | undefined;
    condicoes_medicas?: string | undefined;
    contato_emergencia_nome?: string | undefined;
    contato_emergencia_tel?: string | undefined;
}, {
    nome?: string | undefined;
    genero?: "M" | "F" | undefined;
    data_nascimento?: string | undefined;
    telefone?: string | undefined;
    email?: string | undefined;
    padrinho_id?: string | null | undefined;
    alergias?: string | undefined;
    restricoes_alimentares?: string[] | undefined;
    medicamentos?: string | undefined;
    condicoes_medicas?: string | undefined;
    contato_emergencia_nome?: string | undefined;
    contato_emergencia_tel?: string | undefined;
}>;
export declare const CreateEventoDTO: z.ZodObject<Omit<{
    id: z.ZodOptional<z.ZodString>;
    nome: z.ZodString;
    descricao: z.ZodOptional<z.ZodString>;
    data_inicio: z.ZodString;
    data_fim: z.ZodString;
    local_id: z.ZodString;
    valor_inscricao_encontrista: z.ZodNumber;
    valor_inscricao_servo: z.ZodNumber;
    capacidade_maxima: z.ZodNumber;
    status: z.ZodEnum<["rascunho", "aberto", "encerrado", "realizado"]>;
    created_at: z.ZodOptional<z.ZodString>;
    updated_at: z.ZodOptional<z.ZodString>;
}, "id" | "created_at" | "updated_at">, "strip", z.ZodTypeAny, {
    status: "rascunho" | "aberto" | "encerrado" | "realizado";
    nome: string;
    local_id: string;
    data_inicio: string;
    data_fim: string;
    valor_inscricao_encontrista: number;
    valor_inscricao_servo: number;
    capacidade_maxima: number;
    descricao?: string | undefined;
}, {
    status: "rascunho" | "aberto" | "encerrado" | "realizado";
    nome: string;
    local_id: string;
    data_inicio: string;
    data_fim: string;
    valor_inscricao_encontrista: number;
    valor_inscricao_servo: number;
    capacidade_maxima: number;
    descricao?: string | undefined;
}>;
export declare const UpdateEventoDTO: z.ZodObject<{
    status: z.ZodOptional<z.ZodEnum<["rascunho", "aberto", "encerrado", "realizado"]>>;
    nome: z.ZodOptional<z.ZodString>;
    local_id: z.ZodOptional<z.ZodString>;
    descricao: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    data_inicio: z.ZodOptional<z.ZodString>;
    data_fim: z.ZodOptional<z.ZodString>;
    valor_inscricao_encontrista: z.ZodOptional<z.ZodNumber>;
    valor_inscricao_servo: z.ZodOptional<z.ZodNumber>;
    capacidade_maxima: z.ZodOptional<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    status?: "rascunho" | "aberto" | "encerrado" | "realizado" | undefined;
    nome?: string | undefined;
    local_id?: string | undefined;
    descricao?: string | undefined;
    data_inicio?: string | undefined;
    data_fim?: string | undefined;
    valor_inscricao_encontrista?: number | undefined;
    valor_inscricao_servo?: number | undefined;
    capacidade_maxima?: number | undefined;
}, {
    status?: "rascunho" | "aberto" | "encerrado" | "realizado" | undefined;
    nome?: string | undefined;
    local_id?: string | undefined;
    descricao?: string | undefined;
    data_inicio?: string | undefined;
    data_fim?: string | undefined;
    valor_inscricao_encontrista?: number | undefined;
    valor_inscricao_servo?: number | undefined;
    capacidade_maxima?: number | undefined;
}>;
export declare const CreateInscricaoDTO: z.ZodObject<Omit<{
    id: z.ZodOptional<z.ZodString>;
    evento_id: z.ZodString;
    pessoa_id: z.ZodString;
    papel: z.ZodEnum<["encontrista", "servo"]>;
    valor_total: z.ZodNumber;
    valor_pago: z.ZodNumber;
    cama_id: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    observacoes: z.ZodOptional<z.ZodString>;
    created_at: z.ZodOptional<z.ZodString>;
    updated_at: z.ZodOptional<z.ZodString>;
}, "id" | "created_at" | "updated_at">, "strip", z.ZodTypeAny, {
    evento_id: string;
    pessoa_id: string;
    papel: "encontrista" | "servo";
    valor_total: number;
    valor_pago: number;
    cama_id?: string | null | undefined;
    observacoes?: string | undefined;
}, {
    evento_id: string;
    pessoa_id: string;
    papel: "encontrista" | "servo";
    valor_total: number;
    valor_pago: number;
    cama_id?: string | null | undefined;
    observacoes?: string | undefined;
}>;
export declare const CreatePagamentoDTO: z.ZodObject<Omit<{
    id: z.ZodOptional<z.ZodString>;
    inscricao_id: z.ZodString;
    valor: z.ZodNumber;
    forma_pagamento: z.ZodEnum<["pix", "dinheiro", "cartao", "outro"]>;
    data_pagamento: z.ZodString;
    comprovante_url: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    registrado_por: z.ZodOptional<z.ZodString>;
    created_at: z.ZodOptional<z.ZodString>;
}, "id" | "created_at">, "strip", z.ZodTypeAny, {
    inscricao_id: string;
    valor: number;
    forma_pagamento: "pix" | "dinheiro" | "cartao" | "outro";
    data_pagamento: string;
    comprovante_url?: string | null | undefined;
    registrado_por?: string | undefined;
}, {
    inscricao_id: string;
    valor: number;
    forma_pagamento: "pix" | "dinheiro" | "cartao" | "outro";
    data_pagamento: string;
    comprovante_url?: string | null | undefined;
    registrado_por?: string | undefined;
}>;
export declare const CreateDespesaDTO: z.ZodObject<Omit<{
    id: z.ZodOptional<z.ZodString>;
    evento_id: z.ZodString;
    descricao: z.ZodString;
    categoria: z.ZodEnum<["alimentacao", "transporte", "material", "hospedagem", "outro"]>;
    valor: z.ZodNumber;
    data_despesa: z.ZodString;
    comprovante_url: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    registrado_por: z.ZodOptional<z.ZodString>;
    created_at: z.ZodOptional<z.ZodString>;
}, "id" | "created_at">, "strip", z.ZodTypeAny, {
    descricao: string;
    evento_id: string;
    valor: number;
    categoria: "outro" | "alimentacao" | "transporte" | "material" | "hospedagem";
    data_despesa: string;
    comprovante_url?: string | null | undefined;
    registrado_por?: string | undefined;
}, {
    descricao: string;
    evento_id: string;
    valor: number;
    categoria: "outro" | "alimentacao" | "transporte" | "material" | "hospedagem";
    data_despesa: string;
    comprovante_url?: string | null | undefined;
    registrado_por?: string | undefined;
}>;
export type Pessoa = z.infer<typeof PessoaSchema>;
export type Local = z.infer<typeof LocalSchema>;
export type Quarto = z.infer<typeof QuartoSchema>;
export type Cama = z.infer<typeof CamaSchema>;
export type Evento = z.infer<typeof EventoSchema>;
export type Inscricao = z.infer<typeof InscricaoSchema>;
export type Pagamento = z.infer<typeof PagamentoSchema>;
export type Despesa = z.infer<typeof DespesaSchema>;
export type CreatePessoa = z.infer<typeof CreatePessoaDTO>;
export type UpdatePessoa = z.infer<typeof UpdatePessoaDTO>;
export type CreateEvento = z.infer<typeof CreateEventoDTO>;
export type UpdateEvento = z.infer<typeof UpdateEventoDTO>;
export type CreateInscricao = z.infer<typeof CreateInscricaoDTO>;
export type CreatePagamento = z.infer<typeof CreatePagamentoDTO>;
export type CreateDespesa = z.infer<typeof CreateDespesaDTO>;
export type Genero = z.infer<typeof GeneroEnum>;
export type Papel = z.infer<typeof PapelEnum>;
export type StatusPagamento = z.infer<typeof StatusPagamentoEnum>;
export type StatusEvento = z.infer<typeof StatusEventoEnum>;
export type FormaPagamento = z.infer<typeof FormaPagamentoEnum>;
export type CategoriaDespesa = z.infer<typeof CategoriaDespesaEnum>;
export type GeneroQuarto = z.infer<typeof GeneroQuartoEnum>;
export type TipoCama = z.infer<typeof TipoCamaEnum>;
export type UserRole = z.infer<typeof UserRoleEnum>;
//# sourceMappingURL=index.d.ts.map